services:
  nginx:
    image: nginx:1.13.7
    container_name: nginx-examen
    depends_on:
      - flask
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    ports:
      - 80:80
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flask:0.0.1
    container_name: flask-examen
    volumes:
      - ./code/:/code/
    environment:
      - FLASK_APP=/code/main.py
    command: flask run --host=0.0.0.0
    networks:
      my-network:
        aliases:
          - flask-app
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: docker-postgres_ex
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docker_postgres_dbex
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports: #pasar del puerto interno 5432 al 5432 de mi PC
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
